### ISSUE TITLE
Badge link problems in readme

### ISSUE THREAD

**Issue by cicirello** [silentsoft/nullify#2]
It would be nice if maven badge in readme was linked to: https://search.maven.org/artifact/org.silentsoft/nullify to take visitors directly to maven central artifact without need to search.

Also the build badge's link to travis gives a 404 error.

**Comment by silentsoft** [comment]
I hadn't thought of linking to Maven. I think that's a good idea. 👍 

By the way, it seems that there was a change in the url structure when changing from travis-ci.org to travis-ci.com. Thanks for letting me know.
